
CREATE TABLE IF NOT EXISTS NICKNAMES (
  ID BIGINT IDENTITY PRIMARY KEY,
  NICKNAME VARCHAR_IGNORECASE NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CHANNELS (
  ID BIGINT IDENTITY PRIMARY KEY,
  CHANNEL VARCHAR_IGNORECASE NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS EMOTES (
  ID BIGINT PRIMARY KEY,
  EMOTE VARCHAR NOT NULL,
  SM BLOB,
  MD BLOB,
  LG BLOB
);

CREATE TABLE IF NOT EXISTS CHATS (
  ID BIGINT IDENTITY PRIMARY KEY,
  TIMESTAMP TIMESTAMP NOT NULL,
  NICKNAME_COLOR VARCHAR_IGNORECASE(7) NOT NULL,
  NICKNAME_ID BIGINT NOT NULL,
  CHANNEL_ID BIGINT NOT NULL,
  TEXT VARCHAR NOT NULL,
  CONSTRAINT CHATS_NICK_FK FOREIGN KEY(NICKNAME_ID)
    REFERENCES NICKNAMES(ID),
  CONSTRAINT CHATS_CHAN_FK FOREIGN KEY(CHANNEL_ID)
    REFERENCES CHANNELS(ID)
);

CREATE TABLE IF NOT EXISTS EMOTES_IN_CHAT (
  CHAT_ID BIGINT NOT NULL,
  EMOTE_ID BIGINT NOT NULL,
  START BIGINT NOT NULL,
  END BIGINT NOT NULL,
  CONSTRAINT EMOTES_CHAT_FK FOREIGN KEY(CHAT_ID)
    REFERENCES CHATS(ID),
  CONSTRAINT EMOTES_ID_FK FOREIGN KEY(EMOTE_ID)
    REFERENCES EMOTES(ID),
  CONSTRAINT EMOTES_UNIQUE_START UNIQUE(CHAT_ID, START),
  CONSTRAINT EMOTES_UNIQUE_END UNIQUE(CHAT_ID, END)
);

CREATE TABLE IF NOT EXISTS HUE_COMMANDS_IN_CHAT (
  CHAT_ID BIGINT NOT NULL,
  RED BIGINT NOT NULL,
  GREEN BIGINT NOT NULL,
  BLUE BIGINT NOT NULL,
  CONSTRAINT HUE_CHAT_FK FOREIGN KEY(CHAT_ID)
  REFERENCES CHATS(ID),
  CONSTRAINT HUE_ONE_PER_CHAT UNIQUE(CHAT_ID),
)




